name: ex03_text # 프로젝트의 이름
description: "A new Flutter project." # 프로젝트에 대한 간단한 설명

# 이 패키지를 pub.dev에 게시할지 여부를 결정합니다. 'none'으로 설정되어 있어 게시되지 않습니다.
publish_to: 'none'

# 프로젝트의 버전 정보
version: 1.0.0+1 # +1은 빌드 번호를 나타냅니다

# 이 프로젝트가 작동하는 데 필요한 Flutter SDK의 최소 버전을 지정합니다. 
# 여기서는 SDK 버전 3.8.1 이상이 필요합니다.
environment:
  sdk: ^3.8.1

#  프로젝트가 실행될 때 필요한 패키지
dependencies:
  # Flutter 프레임워크 자체를 사용하기 위해 선언합니다
  flutter:
    sdk: flutter

  # iOS 스타일의 아이콘을 사용하기 위한 패키지입니다
  cupertino_icons: ^1.0.8

# 개발 단계에서만 필요한 패키지들입니다. 빌드 시에는 포함되지 않습니다.
dev_dependencies:
  # 위젯 테스트를 위한 패키지입니다.
  flutter_test:
    sdk: flutter

  # 코드의 스타일 가이드와 규칙을 검사하는 데 사용되는 패키지입니다
  flutter_lints: ^5.0.0

# Flutter 관련 설정을 정의하는 섹션입니다.
flutter:

  # Material 디자인을 사용할지 여부를 지정합니다. 
  # true로 설정하면 앱에서 Material 아이콘 및 테마를 사용할 수 있습니다.
  uses-material-design: true

  # 이미지, 오디오 파일 등 앱에 포함시킬 에셋을 지정하는 섹션입니다
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 앱에 사용할 사용자 정의 글꼴을 추가하는 섹션입니다
  # example:
  fonts:
    - family: D2Coding
      fonts:
        - asset: assets/fonts/D2Coding.ttf
        - asset: assets/fonts/D2Coding.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

